Repository CSC485A-Slacker/slacker, pull requests merged in 2022-03, with the labels that each got.

#30 Check in
  src/Router.tsx
  src/assets/flame1.png
  src/assets/flame2.png
  src/assets/flame3.png
  src/components/PinInfoOverlay.tsx
  src/data/DataConverters.ts
  src/data/Database.ts
  src/data/Interfaces.ts
  src/data/Pin.ts
  src/package-lock.json
  src/redux/PinSlice.ts
  src/screens/Map/CheckInDetailsScreen.tsx
  src/screens/Map/CheckInScreen.tsx
  src/screens/Map/MapScreen.tsx
Labels: feature, milestone 2

#32 Hotspot toggle
  src/screens/Map/MapScreen.tsx
  src/screens/Map/PinDetailsScreen.tsx
Labels: feature, milestone 2

#29 Dev navigation
  src/App.tsx
  src/Router.tsx
  src/redux/PinSlice.ts
  src/screens/Login/LoginScreen.tsx
  src/screens/Map/MapScreen.tsx
  src/screens/Profile/ProfileScreen.tsx
Labels: Enhancement, milestone 2

#40 Align UI Across all Screens
  src/App.tsx
  src/Router.tsx
  src/components/PhotoItem.tsx
  src/components/PinInfoOverlay.tsx
  src/screens/Login/LoginScreen.tsx
  src/screens/Login/RegisterScreen.tsx
  src/screens/Map/AddPhotoScreen.tsx
  src/screens/Map/AddReviewScreen.tsx
  src/screens/Map/CheckInDetailsScreen.tsx
  src/screens/Map/MapScreen.tsx
  src/screens/Map/PinDetailsScreen.tsx
  src/screens/Profile/ProfileScreen.tsx
  src/style/styles.tsx
Labels: Enhancement

#52 Implement Private pins
  src/data/DataConverters.ts
  src/data/Interfaces.ts
  src/data/Pin.ts
  src/redux/PinSlice.ts
  src/screens/Map/MapScreen.tsx
  src/screens/Map/PinDetailsScreen.tsx
Labels: feature, milestone 3, Extensions

#53 implement toast notifications
  src/App.tsx
  src/screens/Map/MapScreen.tsx
  src/screens/Map/PinDetailsScreen.tsx
Labels: Enhancement, milestone 3

#55 Change Pin colors
  src/screens/Map/MapScreen.tsx
  src/screens/Map/PinDetailsScreen.tsx
Labels: Enhancement, milestone 3
